# Generated by Django 3.1.6 on 2021-02-15 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_tweets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemSubmission',
            new_name='ItemSubmissionDate',
        ),
        migrations.AlterModelOptions(
            name='itemsubmissiondate',
            options={'ordering': ['-create_date']},
        ),
    ]
