# Generated by Django 3.1.6 on 2021-02-15 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20210215_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='item_submissions',
            new_name='item_submissions_date',
        ),
    ]
