# Generated by Django 3.1.6 on 2021-02-16 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20210215_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='customer',
        ),
        migrations.AddField(
            model_name='itemsubmissiondate',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_submissions_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='customer.itemsubmissiondate'),
        ),
    ]
