# Generated by Django 3.1.6 on 2021-02-22 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20210219_0746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemsubmissiondate',
            options={},
        ),
    ]
