# Generated by Django 3.1.6 on 2021-02-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20210223_0312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweets',
            name='user_name',
        ),
        migrations.AddField(
            model_name='tweets',
            name='subscribers_count',
            field=models.IntegerField(null=True),
        ),
    ]
