# Generated by Django 3.1.6 on 2021-02-26 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_auto_20210226_0734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweets',
            old_name='subscribers_count',
            new_name='created_utc',
        ),
    ]
